version: '3.3'

services:
  node:
    container_name: hardhat-node
    build:
      context: .
      dockerfile: ./infra/.dockerfile
    image: hardhat-node
    ports: 
      - 8545:8545
    networks:
      - localhost

networks:
  localhost: {}