version: '3.3'

services:
  node:
    container_name: hardhat-node
    build:
      context: .
      dockerfile: ./infra/.dockerfile
    image: hardhat-node
    ports: 
      - 8545:8545
    networks:
      - network
  client:
    container_name: client
    build: 
      context: ./marketplace
      dockerfile: ./infra/.dockerfile-dev
    image: marketplace-client
    # env_file:
    #   - ./marketplace/.env
    ports:
      - 3000:3000
    networks:
      - network

networks:
  network: {}